"""empty message

Revision ID: 62494ebd426e
Revises: 7e5834439f56
Create Date: 2022-11-07 19:48:06.905981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62494ebd426e'
down_revision = '7e5834439f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'goal_id')
    # ### end Alembic commands ###
