"""empty message

Revision ID: 822f236147dc
Revises: b70a3e1a7483
Create Date: 2022-11-05 16:52:54.768288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '822f236147dc'
down_revision = 'b70a3e1a7483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('description', sa.String(), nullable=True))
    op.add_column('task', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'title')
    op.drop_column('task', 'description')
    op.drop_column('task', 'completed_at')
    # ### end Alembic commands ###
